version: "3.9"
services:
  web:
    container_name: web-apache
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./../public:/var/www/html
      - ./../:/var/www
    depends_on:
      - db
    links:
      - db
  db:
    container_name: db-mysql
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '3360:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=sisyourfile